title: "CASM"
description: >
  CASM: A long-term Consistent Artificial-intelligence based Soil Moisture dataset based on machine learning and remote sensing
recipes:
  - id: "casm"
    object: "recipe:casm"
provenance:
  providers:
    - name: "Zenodo"
      description: "https://zenodo.org/records/7072512#.Y01cQi-B2-u"
      roles:
        - DOI
maintainers:
  - name: "Raphael Hagen"
    github: norlandrhagen
  - name: "Mitra Cattry"
    github: mitraA90
